import {
  BrushCleaning,
  Captions,
  Diamond,
  Sparkles,
  Square,
  StepForward,
  Wand2,
} from "lucide-react"

import type { Palette, RulePreset, ScenePreset, ToolDefinition } from "../types"

export const palettes: Palette[] = [
  { key: "petri", label: "Petri", background: "#070d0b", cell: "#dfffe4", grid: "#203129", trail: "#143026" },
  { key: "mycelium", label: "Mycelium", background: "#0f1116", cell: "#eee6d0", grid: "#252935", trail: "#433349" },
  { key: "biofilm", label: "Biofilm", background: "#061211", cell: "#95ffbc", grid: "#12332a", trail: "#1d5d47" },
  { key: "ember", label: "Ember", background: "#120b0d", cell: "#ffb080", grid: "#3b262b", trail: "#4f272f" },
  { key: "neon-ice", label: "Neon Ice", background: "#060b14", cell: "#8ce8ff", grid: "#1b2d4f", trail: "#134166" },
  { key: "ultraviolet", label: "Ultraviolet", background: "#0b0714", cell: "#c9a2ff", grid: "#2f2150", trail: "#4d2e7a" },
  { key: "sunset-grid", label: "Sunset Grid", background: "#12080a", cell: "#ff9e8c", grid: "#4c2530", trail: "#7a3444" },
  { key: "acid-lime", label: "Acid Lime", background: "#081006", cell: "#d3ff7a", grid: "#24361c", trail: "#416224" },
  { key: "steel-blue", label: "Steel Blue", background: "#0b1117", cell: "#c9d9ff", grid: "#26384b", trail: "#37506d" },
  { key: "rose-lab", label: "Rose Lab", background: "#120b10", cell: "#ffb7d9", grid: "#45243a", trail: "#6a3452" },
  { key: "paper-mint", label: "Paper Mint", background: "#f3fff7", cell: "#0f553a", grid: "#d8ebe1", trail: "#95bea8" },
  { key: "daylight-blue", label: "Daylight Blue", background: "#f4f8ff", cell: "#3356a6", grid: "#d7e1fb", trail: "#93aae0" },
  { key: "warm-paper", label: "Warm Paper", background: "#fff7ef", cell: "#9a552f", grid: "#efd6c4", trail: "#d9a584" },
  { key: "graphite-paper", label: "Graphite Paper", background: "#f5f4ef", cell: "#23282c", grid: "#d9ddd8", trail: "#acb3ad" },
]

export const rules: RulePreset[] = [
  { key: "conway", label: "Conway", description: "Balanced Life with gliders and stable forms.", birth: [3], survive: [2, 3], density: 0.22 },
  { key: "coagulation", label: "Coagulation", description: "Thick colony membranes and clotted growth.", birth: [3, 7, 8], survive: [2, 3, 5, 6, 7, 8], density: 0.35 },
  { key: "serviettes", label: "Serviettes", description: "Lacy explosive branching like fungal fronts.", birth: [2, 3, 4], survive: [], density: 0.08 },
  { key: "maze", label: "Maze", description: "Creases into creeping labyrinths and dense channels.", birth: [3], survive: [1, 2, 3, 4, 5], density: 0.24 },
  { key: "coral", label: "Coral", description: "Porous rim growth and chunky accretion.", birth: [3], survive: [4, 5, 6, 7, 8], density: 0.28 },
]

export const scenes: ScenePreset[] = [
  {
    key: "blank-canvas",
    label: "Blank Canvas",
    description: "Classic Conway setup with a clean title stamp ready to animate.",
    seedMode: "title",
    ruleKey: "conway",
    paletteKey: "petri",
    density: 0.22,
    speed: 8,
    trail: 0.24,
    gridContrast: 0.08,
    cellSize: 7,
    showGrid: false,
  },
  {
    key: "bacterial-bloom",
    label: "Bacterial Bloom",
    description: "Clustered petri colonies with membranes and speckled spillover.",
    seedMode: "petri-colonies",
    ruleKey: "coagulation",
    paletteKey: "petri",
    density: 0.34,
    speed: 10,
    trail: 0.36,
    gridContrast: 0.08,
    cellSize: 7,
    showGrid: false,
  },
  {
    key: "fungal-mycelium",
    label: "Fungal Mycelium",
    description: "Root-like tendrils and branching runners instead of static noise.",
    seedMode: "root-network",
    ruleKey: "serviettes",
    paletteKey: "mycelium",
    density: 0.08,
    speed: 7,
    trail: 0.48,
    gridContrast: 0.06,
    cellSize: 6,
    showGrid: false,
  },
  {
    key: "coral-colony",
    label: "Coral Colony",
    description: "Chunky porous reefs with hollow pockets and branching shelves.",
    seedMode: "coral-clusters",
    ruleKey: "coral",
    paletteKey: "biofilm",
    density: 0.26,
    speed: 9,
    trail: 0.24,
    gridContrast: 0.06,
    cellSize: 7,
    showGrid: false,
  },
  {
    key: "ember-plate",
    label: "Smiley Reactor",
    description: "A goofy ember smiley ringed with sparks before it melts into channels.",
    seedMode: "smiley-burst",
    ruleKey: "maze",
    paletteKey: "ember",
    density: 0.22,
    speed: 8,
    trail: 0.41,
    gridContrast: 0.12,
    cellSize: 7,
    showGrid: false,
  },
]

export const tools: ToolDefinition[] = [
  { key: "brush", label: "Brush", icon: BrushCleaning, kind: "paint", pattern: [[1]] },
  { key: "block", label: "Block", icon: Square, kind: "stamp", pattern: [[1, 1], [1, 1]] },
  { key: "glider", label: "Glider", icon: StepForward, kind: "stamp", pattern: [[0, 1, 0], [0, 0, 1], [1, 1, 1]] },
  { key: "cross", label: "Cross", icon: Sparkles, kind: "stamp", pattern: [[0, 1, 0], [1, 1, 1], [0, 1, 0]] },
  { key: "diamond", label: "Diamond", icon: Diamond, kind: "stamp", pattern: [[0, 1, 0], [1, 1, 1], [0, 1, 0]] },
  { key: "exploder", label: "Exploder", icon: Wand2, kind: "stamp", pattern: [[1, 0, 1], [1, 0, 1], [1, 0, 1], [1, 0, 1], [1, 0, 1]] },
  { key: "text", label: "Text", icon: Captions, kind: "action" },
  { key: "noise", label: "Noise", icon: Sparkles, kind: "action" },
]
